# Generated by Django 5.0.7 on 2024-07-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("title", models.CharField(max_length=250)),
                ("url", models.TextField(primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "NEWSITES",
                "managed": False,
            },
        ),
    ]
