# Generated by Django 5.0.7 on 2024-07-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Records",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("First_Name", models.CharField(max_length=255)),
                ("Last_Name", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=254)),
                ("City", models.CharField(max_length=255)),
                ("Phone", models.CharField(max_length=255)),
            ],
        ),
    ]
