# Generated by Django 5.0.7 on 2024-07-28 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Records",
            new_name="Record",
        ),
    ]
