# Generated by Django 5.1 on 2024-08-27 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="password",
            new_name="number",
        ),
    ]
